// Auto-generated TypeScript types from database schema
// DO NOT EDIT MANUALLY - This file is generated by generate_database_types tool

export interface AiApiKeysS7B4A66883Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  config_id: number;
  key_name: string;
  api_key: string;
  is_enabled: string | null;
  last_used_at: string | null;
  usage_count: number | null;
  expires_at: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type AiApiKeysS7B4A66883Insert = Omit<AiApiKeysS7B4A66883Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type AiApiKeysS7B4A66883Update = Partial<AiApiKeysS7B4A66883Insert>;

export interface AiCallLogsS7B4A66883Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  config_id: number;
  key_id: number | null;
  request_tokens: number | null;
  response_tokens: number | null;
  status: string;
  error_message: string | null;
  latency_ms: number | null;
  request_body: string | null;
  response_body: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type AiCallLogsS7B4A66883Insert = Omit<AiCallLogsS7B4A66883Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type AiCallLogsS7B4A66883Update = Partial<AiCallLogsS7B4A66883Insert>;

export interface AiModelConfigsS7B4A66883Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  model_name: string;
  provider: string;
  api_endpoint: string;
  default_max_tokens: number | null;
  default_temperature: number | null;
  is_enabled: string | null;
  description: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type AiModelConfigsS7B4A66883Insert = Omit<AiModelConfigsS7B4A66883Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type AiModelConfigsS7B4A66883Update = Partial<AiModelConfigsS7B4A66883Insert>;
